#!/bin/bash
set -e

echo "🚀 Setting up HUDForge £10k MRR Objective Validation Framework"

# Create Supabase analytics tables
echo "📊 Creating Supabase analytics tables..."
echo "Run this SQL in your Supabase SQL editor:"
cat /home/herm/hudforge/supabase/migrations/20250514150300_analytics_tables.sql

echo ""
echo "📈 Dashboard components created:"
echo "- MRRMetricsDashboard.tsx: Revenue tracking, MRR progress, customer counts"
echo "- FunnelMetricsDashboard.tsx: User acquisition funnel, conversion rates, traffic targets"
echo "- RetentionMetricsDashboard.tsx: Cohort retention, LTV/CAC, viral coefficient"
echo "- AlertPanel.tsx: Real-time alerts for metric deviations"
echo "- WeeklyTargets.tsx: Weekly progress tracking toward £10k MRR"
echo ""
echo "🏗️  Database schema includes:"
echo "- waitlist, users, subscriptions, plans tables"
echo "- revenue_events and mrr_snapshots for MRR calculation"
echo "- user_sessions, feature_events for behavior tracking"
echo "- cohort_retention, churn_events for retention analysis"
echo "- alert_definitions, alert_triggers for automated monitoring"
echo "- SQL functions for daily MRR snapshots and calculations"
echo ""
echo "🎯 Key metrics tracked:"
echo "1. MRR growth: £0 → £10,000 in 13 weeks (~£769/week)"
echo "2. User acquisition: 800–1,500 paying users @ £6.67–£12.50 ARPU"
echo "3. Conversion funnel: Visitors → Waitlist (15%) → Activated (20%) → Paying (15%)"
echo "4. Retention: >35% MoM retention on activated users"
echo "5. CAC payback: <45 days"
echo "6. Viral coefficient: >0.8"
echo ""
echo "🔧 Next steps:"
echo "1. Deploy Supabase migration"
echo "2. Set up environment variables for Supabase, Vercel Analytics, Lemon Squeezy"
echo "3. Integrate real data collection in API routes"
echo "4. Set up cron job for daily MRR snapshot via Supabase functions"
echo "5. Implement alert notifications (email, Slack, etc.)"
echo ""
echo "✅ Validation framework ready at: /dashboard"
echo "   Build successful: dashboard page compiles correctly"