import type { Metadata } from 'next'
import Image from 'next/image'
import Link from 'next/link'

export const metadata: Metadata = {
  title: 'HUDForge | Build Roblox UI Systems at Game Speed',
  description: 'Turn prompts into structured Roblox UI systems, preview layouts, and export implementation-ready packages with HUDForge.',
}

const metrics = [
  ['12,400+', 'Creators onboarded'],
  ['1.8M+', 'Assets exported'],
  ['58%', 'Avg. build-time reduction'],
  ['4.9/5', 'Satisfaction score'],
]

export default function Home() {
  return (
    <main className="min-h-screen bg-[#EEF3FB] text-[#1E2430]">
      <header className="sticky top-0 z-50 border-b border-[#DCE5F3]/80 bg-white/70 backdrop-blur-xl">
        <div className="mx-auto flex max-w-[1280px] items-center justify-between px-5 py-4 sm:px-6 lg:px-8">
          <Link href="/" className="flex items-center gap-3 font-bold"><span className="rounded-xl bg-gradient-to-br from-[#F55CCF] to-[#8C7BFF] px-2 py-1 text-white">HF</span>HUDForge</Link>
          <nav className="hidden items-center gap-6 text-sm font-medium lg:flex">{['Features','Templates','Pricing','Results','FAQ'].map(i=><a key={i} href={`#${i.toLowerCase()}`} className="text-[#5E677A] hover:text-[#1E2430]">{i}</a>)}</nav>
          <div className="hidden items-center gap-3 lg:flex"><Link href="/sign-in" className="rounded-full border border-[#DCE5F3] bg-white px-4 py-2 text-sm">Sign in</Link><Link href="/sign-up" className="rounded-full bg-gradient-to-r from-[#F55CCF] to-[#8C7BFF] px-5 py-2 text-sm font-semibold text-white">Start Building</Link></div>
          <details className="lg:hidden"><summary className="list-none rounded-lg border border-[#DCE5F3] bg-white px-3 py-2">☰</summary><div className="fixed inset-0 z-50 bg-[#EEF3FB] p-8"><div className="mb-8 flex justify-between"><Link href="/sign-up" className="rounded-full bg-gradient-to-r from-[#F55CCF] to-[#8C7BFF] px-5 py-3 font-semibold text-white">Start Building</Link></div><div className="grid gap-4 text-2xl">{['Features','Templates','Pricing','Results','FAQ'].map(i=><a key={i} href={`#${i.toLowerCase()}`}>{i}</a>)}</div></div></details>
        </div>
      </header>

      <section className="relative overflow-hidden px-5 pb-20 pt-12 sm:px-6 lg:px-8">
        <div className="absolute inset-0 -z-10" style={{background:'linear-gradient(135deg, #FDEBFF 0%, #EAF7FF 35%, #E9FFF6 100%)'}} />
        <div className="absolute inset-0 -z-10" style={{background:'radial-gradient(circle at 20% 20%, rgba(245,92,207,.22), transparent 40%), radial-gradient(circle at 80% 30%, rgba(79,216,255,.22), transparent 45%)'}} />
        <div className="mx-auto grid max-w-[1280px] gap-10 lg:grid-cols-[1fr_1.1fr] lg:items-center">
          <div><p className="text-sm font-semibold uppercase tracking-wide text-[#5E677A]">Roblox-first workflow SaaS</p><h1 className="mt-4 text-5xl font-extrabold leading-[1.05] sm:text-6xl">Build Roblox UI Systems at Game Speed</h1><p className="mt-5 max-w-xl text-lg leading-8 text-[#5E677A]">Describe the UI you want, preview production-ready layouts, and export implementation-ready package structure your team can ship fast.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/sign-up" className="min-h-12 rounded-full bg-gradient-to-r from-[#F55CCF] to-[#8C7BFF] px-6 py-3 font-semibold text-white">Start Building</Link><a href="#templates" className="min-h-12 rounded-full border border-[#DCE5F3] bg-white px-6 py-3 font-semibold">See Templates</a></div><div className="mt-6 flex flex-wrap gap-3 text-sm">{['Roblox-first workflow','Preview before export','UI system consistency'].map(b=><span key={b} className="rounded-full border border-[#DCE5F3] bg-white/90 px-4 py-2">{b}</span>)}</div></div>
          <div className="relative min-h-[420px]"><Image src="/generated/marketing/hf-hero-cinematic.png.svg" alt="Stylized Roblox creators collaborating around UI screens" fill priority className="rounded-[24px] border border-[#DCE5F3] object-cover shadow-xl" /><div className="absolute left-4 top-6 rounded-2xl border border-[#DCE5F3] bg-white/90 p-3 text-xs">Quest Tracker • Ready</div><div className="absolute bottom-6 left-6 rounded-2xl border border-[#DCE5F3] bg-white/90 p-3 text-xs">Inventory Grid • Synced</div><div className="absolute bottom-10 right-6 rounded-2xl border border-[#DCE5F3] bg-white/90 p-3 text-xs">Shop Button States • Exported</div></div>
        </div>
      </section>

      <section className="px-5 py-8 sm:px-6 lg:px-8"><div className="mx-auto grid max-w-[1280px] gap-4 md:grid-cols-4">{metrics.map(([v,l])=><article key={l} className="rounded-2xl border border-[#DCE5F3] bg-[#FDFEFF] p-5"><p className="text-2xl font-bold">{v}</p><p className="text-sm text-[#5E677A]">{l}</p></article>)}</div></section>
      <section id="features" className="px-5 py-20 sm:px-6 lg:px-8"><div className="mx-auto max-w-[1280px]"><h2 className="text-4xl font-bold">Features built for shipping teams</h2><div className="mt-8 grid gap-6 md:grid-cols-2 lg:grid-cols-3">{['Prompt to UI structure','Style-consistent screens','Asset pack generation','Live layout preview','Team-ready handoff','Fast design iteration'].map((f,i)=><article key={f} className="group rounded-[20px] border border-[#DCE5F3] bg-white p-5 shadow-sm transition hover:-translate-y-1"><Image src={`/generated/marketing/feature-${i+1}.png`} alt={f} width={420} height={220} className="h-36 w-full rounded-xl object-cover" /><h3 className="mt-4 text-xl font-semibold">{f}</h3><p className="mt-2 text-[#5E677A]">{['Convert intent into reusable Roblox UI hierarchies.','Keep HUD, menus, and popups visually aligned across updates.','Generate UI-ready sprites, panels, and visual parts in one flow.','Preview interactions before exporting to implementation packages.','Share predictable package structures with designers and scripters.','Cut wasted revisions with faster version loops.'][i]}</p><Link href="/sign-up" className="mt-4 inline-block text-sm font-semibold text-[#8C7BFF]">Start Building →</Link></article>)}</div></div></section>
      <section className="px-5 py-20 sm:px-6 lg:px-8"><div className="mx-auto max-w-[1280px]"><h2 className="text-4xl font-bold">How it works</h2><div className="mt-8 grid gap-6 lg:grid-cols-3">{['Describe','Generate','Export'].map((s,i)=><article key={s} className="relative rounded-3xl border border-[#DCE5F3] bg-white p-6"><Image src={`/generated/marketing/step-${i+1}.png`} alt={`${s} step preview`} width={400} height={220} className="h-32 w-full rounded-xl object-cover"/><h3 className="mt-4 text-2xl font-bold">{s}</h3><p className="mt-2 text-[#5E677A]">{['Type your game goal and UI constraints.','Get structured screens, components, and assets.','Download implementation-ready package sets.'][i]}</p></article>)}</div></div></section>
      <section id="templates" className="px-5 py-20 sm:px-6 lg:px-8"><div className="mx-auto max-w-[1280px]"><div className="flex items-end justify-between"><h2 className="text-4xl font-bold">Template showcase</h2><Link href="/sign-up" className="rounded-full bg-gradient-to-r from-[#F55CCF] to-[#8C7BFF] px-5 py-3 font-semibold text-white">Start Building</Link></div><div className="mt-8 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{['Shop UI','Inventory','Quest HUD','Reward Popup','Main Menu','Daily Login'].map((t,i)=><article key={t} className="rounded-2xl border border-[#DCE5F3] bg-white p-4"><Image src={`/generated/marketing/template-${i+1}.png`} alt={`${t} template preview`} width={420} height={260} className="h-44 w-full rounded-xl object-cover"/><div className="mt-3 flex items-center justify-between"><h3 className="font-semibold">{t}</h3><button className="text-sm font-semibold text-[#8C7BFF]">Use Template</button></div></article>)}</div></div></section>
      <section id="results" className="px-5 py-20 sm:px-6 lg:px-8"><div className="mx-auto grid max-w-[1280px] gap-6 lg:grid-cols-3">{['2.3x faster UI iteration','40% less rework','Higher consistency across screens'].map((r,i)=><article key={r} className="rounded-2xl border border-[#DCE5F3] bg-white p-6"><div className="h-24 rounded-xl" style={{background:['linear-gradient(90deg,#4FD8FF,#63E6BE)','linear-gradient(90deg,#FFD166,#F55CCF)','linear-gradient(90deg,#8C7BFF,#4FD8FF)'][i]}}/><h3 className="mt-4 text-2xl font-bold">{r}</h3><p className="mt-2 text-[#5E677A]">Teams shipped updates with tighter UI quality and clearer production handoffs.</p><Link href="/sign-up" className="mt-3 inline-block text-sm font-semibold text-[#8C7BFF]">Start Building →</Link></article>)}</div></section>
      <section id="pricing" className="px-5 py-20 sm:px-6 lg:px-8"><div className="mx-auto max-w-[1280px]"><h2 className="text-4xl font-bold">Pricing that scales with your game</h2><div className="mt-8 grid gap-6 lg:grid-cols-3">{[['Starter','$29'],['Pro','$79'],['Studio','$199']].map(([n,p])=><article key={n} className={`rounded-3xl border p-6 ${n==='Pro'?'border-transparent bg-[linear-gradient(white,white),linear-gradient(135deg,#F55CCF,#8C7BFF,#4FD8FF)] bg-origin-border bg-clip-padding':'border-[#DCE5F3] bg-white'}`}><h3 className="text-2xl font-bold">{n}</h3><p className="mt-2 text-4xl font-extrabold">{p}<span className="text-base font-medium text-[#5E677A]">/mo</span></p><ul className="mt-4 space-y-2 text-[#5E677A]"><li>Prompt-to-UI generation</li><li>Template library access</li><li>Layout preview + export</li><li>Team collaboration options</li></ul><Link href="/sign-up" className={`mt-6 inline-block w-full rounded-full px-5 py-3 text-center font-semibold ${n==='Pro'?'bg-gradient-to-r from-[#F55CCF] to-[#8C7BFF] text-white':'border border-[#DCE5F3] bg-white'}`}>Start Building</Link></article>)}</div><p className="mt-4 text-center text-sm text-[#5E677A]">Cancel anytime.</p></div></section>
      <section className="px-5 py-20 sm:px-6 lg:px-8"><div className="mx-auto max-w-[1280px]"><h2 className="text-4xl font-bold">Loved by Roblox creators</h2><div className="mt-8 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{['Avery','Rin','Milo','Jules','Kai','Tess'].map((n,i)=><article key={n} className="rounded-2xl border border-[#DCE5F3] bg-white p-5"><div className="flex items-center gap-3"><Image src={`/generated/marketing/avatar-${i+1}.png`} alt={`${n} avatar`} width={48} height={48} className="rounded-full"/><div><p className="font-semibold">{n}</p><p className="text-sm text-[#5E677A]">Studio Builder • RPG</p></div></div><p className="mt-3 text-[#5E677A]">“We went from rough UI ideas to ship-ready screens in a day.”</p></article>)}</div></div></section>
      <section id="faq" className="px-5 py-20 sm:px-6 lg:px-8"><div className="mx-auto max-w-[980px]"><h2 className="text-4xl font-bold">FAQ</h2><div className="mt-6 space-y-3">{['Which export formats are supported?','Does this work with current Roblox UI systems?','Can my whole team collaborate?','Can non-designers use HUDForge?','How billing works for studios?','What support is included?'].map(q=><details key={q} className="rounded-2xl border border-[#DCE5F3] bg-white p-5"><summary className="cursor-pointer font-semibold">{q}</summary><p className="mt-3 text-[#5E677A]">Yes—HUDForge is built for practical production workflows and fast creator iteration.</p></details>)}</div></div></section>
      <section className="px-5 pb-14 sm:px-6 lg:px-8"><div className="mx-auto max-w-[1280px] rounded-[28px] p-10 text-center" style={{background:'linear-gradient(135deg, #FDEBFF 0%, #EAF7FF 35%, #E9FFF6 100%)'}}><h2 className="text-4xl font-bold">Ship your next Roblox UI update faster.</h2><Link href="/sign-up" className="mt-6 inline-block rounded-full bg-gradient-to-r from-[#F55CCF] to-[#8C7BFF] px-8 py-3 font-semibold text-white">Start Building</Link><div className="mt-3"><a href="#pricing" className="text-sm text-[#5E677A]">View Pricing</a></div></div></section>
      <footer className="border-t border-[#DCE5F3] bg-white px-5 py-12 text-sm sm:px-6 lg:px-8"><div className="mx-auto grid max-w-[1280px] gap-6 md:grid-cols-4"><div><h3 className="font-semibold">Product</h3><p className="mt-3 text-[#5E677A]">Features<br/>Templates<br/>Pricing</p></div><div><h3 className="font-semibold">Resources</h3><p className="mt-3 text-[#5E677A]">Docs<br/>Guides<br/>Blog</p></div><div><h3 className="font-semibold">Legal</h3><p className="mt-3 text-[#5E677A]">Terms<br/>Privacy<br/>Refunds</p></div><div><h3 className="font-semibold">Social</h3><p className="mt-3 text-[#5E677A]">X<br/>Discord<br/>YouTube</p></div></div><p className="mx-auto mt-8 max-w-[1280px] text-[#5E677A]">© {new Date().getFullYear()} HUDForge. All rights reserved.</p></footer>
    </main>
  )
}
